### ISSUE TITLE
JS error TypeError: k is not a function 

### ISSUE THREAD

**Issue by for93t** [SpamExperts/aps2-addon#32]
### Version information
2.0-18

### Steps to replicate

 1. In CCP -> Users -> Add New Service User -> Next, then don't wait until domain protection status is loaded (also reproducible if there are no protected domains) and click "Next" again. The "SE Email user won't be created." message will be shown on final screen and an error will be logged in browser console

### Actual result

```
TypeError: k is not a function
    at c (VM1369 aps.js:111)
    at l.then.b.then (VM1369 aps.js:114)
    at VM3501 suwizard.overview.html:23
    at sa (VM1369 aps.js:19)
    at VM1369 aps.js:19
    at ta (VM1369 aps.js:19)
    at qa (VM1369 aps.js:19)
    at e (VM1369 aps.js:20)
    at VM1369 aps.js:804
    at Object.F [as init] (VM1375 i18next.js:10) "TypeError: k is not a function
    at c (http://osa60.lestifeev.apsdemo.org:8080/aps/2/ui/runtime/client/aps/aps.js:111:423)
    at l.then.b.then (http://osa60.lestifeev.apsdemo.org:8080/aps/2/ui/runtime/client/aps/aps.js:114:232)
    at http://osa60.lestifeev.apsdemo.org:8080/aps/2/packages/35b6a53c-3844-4f21-8556-cecb7a3807d8/ui/suwizard.overview.html:23:53
    at sa (http://osa60.lestifeev.apsdemo.org:8080/aps/2/ui/runtime/client/aps/aps.js:19:3)
    at http://osa60.lestifeev.apsdemo.org:8080/aps/2/ui/runtime/client/aps/aps.js:19:240
    at ta (http://osa60.lestifeev.apsdemo.org:8080/aps/2/ui/runtime/client/aps/aps.js:19:125)
    at qa (http://osa60.lestifeev.apsdemo.org:8080/aps/2/ui/runtime/client/aps/aps.js:19:180)
    at e (http://osa60.lestifeev.apsdemo.org:8080/aps/2/ui/runtime/client/aps/aps.js:20:15)
    at http://osa60.lestifeev.apsdemo.org:8080/aps/2/ui/runtime/client/aps/aps.js:804:209
    at Object.F [as init] (http://osa60.lestifeev.apsdemo.org:8080/aps/2/ui/runtime/client/3rd-party/i18next/i18next.js:10:203)
    ----------------------------------------
    rejected at a (http://osa60.lestifeev.apsdemo.org:8080/aps/2/ui/runtime/client/aps/aps.js:112:313)
    at c (http://osa60.lestifeev.apsdemo.org:8080/aps/2/ui/runtime/client/aps/aps.js:112:65)
    at l.then.b.then (http://osa60.lestifeev.apsdemo.org:8080/aps/2/ui/runtime/client/aps/aps.js:114:232)
    at http://osa60.lestifeev.apsdemo.org:8080/aps/2/packages/35b6a53c-3844-4f21-8556-cecb7a3807d8/ui/suwizard.overview.html:23:53
    at sa (http://osa60.lestifeev.apsdemo.org:8080/aps/2/ui/runtime/client/aps/aps.js:19:3)
    at http://osa60.lestifeev.apsdemo.org:8080/aps/2/ui/runtime/client/aps/aps.js:19:240
    at ta (http://osa60.lestifeev.apsdemo.org:8080/aps/2/ui/runtime/client/aps/aps.js:19:125)
    at qa (http://osa60.lestifeev.apsdemo.org:8080/aps/2/ui/runtime/client/aps/aps.js:19:180)
    at e (http://osa60.lestifeev.apsdemo.org:8080/aps/2/ui/runtime/client/aps/aps.js:20:15)
    at http://osa60.lestifeev.apsdemo.org:8080/aps/2/ui/runtime/client/aps/aps.js:804:209
    ----------------------------------------
Error
    at l.then.b.then (http://osa60.lestifeev.apsdemo.org:8080/aps/2/ui/runtime/client/aps/aps.js:114:177)
    at http://osa60.lestifeev.apsdemo.org:8080/aps/2/packages/35b6a53c-3844-4f21-8556-cecb7a3807d8/ui/suwizard.overview.html:23:53
    at sa (http://osa60.lestifeev.apsdemo.org:8080/aps/2/ui/runtime/client/aps/aps.js:19:3)
    at http://osa60.lestifeev.apsdemo.org:8080/aps/2/ui/runtime/client/aps/aps.js:19:240
    at ta (http://osa60.lestifeev.apsdemo.org:8080/aps/2/ui/runtime/client/aps/aps.js:19:125)
    at qa (http://osa60.lestifeev.apsdemo.org:8080/aps/2/ui/runtime/client/aps/aps.js:19:180)
    at e (http://osa60.lestifeev.apsdemo.org:8080/aps/2/ui/runtime/client/aps/aps.js:20:15)
    at http://osa60.lestifeev.apsdemo.org:8080/aps/2/ui/runtime/client/aps/aps.js:804:209
    at Object.F [as init] (http://osa60.lestifeev.apsdemo.org:8080/aps/2/ui/runtime/client/3rd-party/i18next/i18next.js:10:203)
    at p (http://osa60.lestifeev.apsdemo.org:8080/aps/2/ui/runtime/client/aps/aps.js:804:119)"
f @ VM1369 aps.js:118
(anonymous) @ VM1369 aps.js:118
filter @ VM1369 aps.js:49
c @ VM1369 aps.js:118
```
### Expected result

No JS errors

**Comment by for93t** [comment]
This is actual for OSA v6 which is outdated.
