### ISSUE TITLE
"Could not replace MX records for domain" error

### ISSUE THREAD

**Issue by for93t** [SpamExperts/aps2-addon#42]
### Version information
2.0-20

### Steps to replicate

 1. Try to protect a certain domain
 2. Observe the error in logs and the domain is not protected

### Actual result
The domain is not protected and there are errors in logs.

### Expected result
The domain is protected and no errors.

### Other notes
Debug logs:
```
[root@endpoint ~]# tail -fn0 /var/www/html/spamexperts/logs/app-log-2018-07-24
...
[2018-07-24 19:33:15] Context.INFO: replaceMXRecords: Setting up record: protection-02.dotnetwork.co.za. -> mallspaces.co.za. [] []
[2018-07-24 19:33:15] Context.INFO: replaceMXRecords: Linking new record to domain records collection [] []
[2018-07-24 19:33:16] Context.WARNING: [REPORT]: Could not replace MX records for domain 'mallspaces.co.za'. [exception 'Rest\RestException' with message 'Can not create DNS Record for '__host__'. There is an existing __rr_type__ record (__host__ __data__, #__rr_id__) already.' in /usr/share/aps/php/aps/2/apsc.php:383 Stack trace: #0 /usr/share/aps/php/aps/2/apsc.php(989): APS\Proto->sendRequest('POST', 'aps/7.2/resourc...', '{\n "aps": {\n...') #1 /var/www/html/spamexperts/context.php(1106): APS\ControllerProxy->linkResource(Object(com\parallels\aps\types\pa\dns\zone\v1\v1\PAHostedDomain), 'records', Object(com\parallels\aps\types\pa\dns\record\mx\v1\v0\PADnsMXRecord)) #2 /var/www/html/spamexperts/context.php(821): context->replaceMXRecords(Object(com\parallels\aps\types\pa\dns\zone\v1\v1\PAHostedDomain)) #3 /var/www/html/spamexperts/context.php(758): context->protectResource(Object(com\parallels\aps\types\pa\dns\zone\v1\v1\PAHostedDomain)) #4 /var/www/html/spamexperts/context.php(577): context->updateResources(Array, true) #5 [internal function]: context->domainProtect('["0b4c7084-8cad...') #6 /usr/share/aps/php/aps/2/rest.php(1093): call_user_func_array(Array, Array) #7 /usr/share/aps/php/aps/2/runtime.php(402): Rest\RestService->handle() #8 /usr/share/aps/php/aps/2/runtime.php(460): APS\Loader->handleHttpRequest() #9 /usr/share/aps/php/aps/2/runtime.php(472): APS\Loader->process() #10 [internal function]: APS\Loader->__destruct() #11 {main}] [] []
...
[2018-07-24 19:33:16] Context.WARNING: [REPORT]: Failed to replace domain MX records. This is an issue with POA/APS, please contact support for further information. (mallspaces.co.za) [] []
...
[2018-07-24 19:33:16] Context.WARNING: [REPORT]: Domain MX records aren't set correctly. The 'Protect' action may fix this for you, otherwise please contact your service provider. (mallspaces.co.za) [] []
...
```
API response:
```
# curl -k -E /usr/local/pem/APS/certificates/poa.pem 'https://localhost:6308/aps/2/resources/0b4c7084-8cad-4b68-98f3-23cd11a4e289/records?and(implementing(http://parallels.com/aps/types/pa/dns/record/mx/1.0),out(exchange,(protection-01.dotnetwork.co.za.,protection-02.dotnetwork.co.za.)),sort(+priority))'
[
  {
    "aps": {
      "type": "http://parallels.com/aps/types/pa/dns/record/mx/1.0",
      "id": "b75ff167-dd8e-4612-a1ee-0d5fa9ba9965",
      "status": "aps:ready",
      "revision": 2,
      "modified": "2017-01-09T13:32:06Z"
    },
    "RRState": "active",
    "TTL": 3600,
    "exchange": "protection-01.dotnetwork.co.za",
    "priority": 10,
    "recordId": 50079,
    "source": "",
    "sourceFQN": "mallspaces.co.za.",
    "data": "10 protection-01.dotnetwork.co.za."
  },
  {
    "aps": {
      "type": "http://parallels.com/aps/types/pa/dns/record/mx/1.0",
      "id": "4afc30a3-f4f7-463a-9f32-4b866d3ec68d",
      "status": "aps:ready",
      "revision": 3,
      "modified": "2017-01-09T13:32:56Z",
      "subscription": "ec766935-91ca-44ff-bf5e-2f805606ecaf"
    },
    "RRState": "active",
    "TTL": 3600,
    "exchange": "protection-02.dotnetwork.co.za",
    "source": "",
    "priority": 20,
    "recordId": 50080,
    "sourceFQN": "mallspaces.co.za.",
    "data": "20 protection-02.dotnetwork.co.za."
  },
  {
    "aps": {
      "type": "http://parallels.com/aps/types/pa/dns/record/mx/1.0",
      "id": "4b8800d3-eab7-4889-a9c5-e314e67222af",
      "status": "aps:ready",
      "revision": 2,
      "modified": "2017-01-09T13:32:15Z"
    },
    "RRState": "active",
    "TTL": 3600,
    "exchange": "protection-02.dotnetwork.co.za",
    "priority": 20,
    "recordId": 50080,
    "source": "",
    "sourceFQN": "mallspaces.co.za.",
    "data": "20 protection-02.dotnetwork.co.za."
  }
]
```

**Comment by for93t** [comment]
Such an issue can happen when a domain already has MX records set up before the protection is executed and those records have been added by someone who has higher permissions in the OA platform than the application has. Due to that the application just unable to "see" all the existing MX records and attempts to create duplicates. I've added a more detailed explanation to the error message so the case would be identified and, if the directions from the description are followed, can be fixed by the client or with our assistance. That's all that can be done here, I'm afraid.
